# Generated by Django 4.0.6 on 2022-07-25 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicar', '0002_alter_horarios_data_agendamento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agenda',
            options={'ordering': ['data_agenda']},
        ),
        migrations.AddField(
            model_name='agenda',
            name='valido',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='horarios',
            name='valido',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='agenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='medicar.agenda'),
        ),
    ]
