# Generated by Django 4.0.6 on 2022-07-27 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicar', '0003_alter_agenda_options_agenda_valido_horarios_valido_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horarios',
            options={'ordering': ['horario']},
        ),
        migrations.CreateModel(
            name='Consultas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_agendamento', models.DateField()),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='medicar.agenda')),
                ('horarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='medicar.horarios')),
            ],
            options={
                'ordering': ['data_agendamento'],
            },
        ),
    ]
