# Generated by Django 4.0.6 on 2022-07-27 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicar', '0004_alter_horarios_options_consultas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horarios',
            name='data_agendamento',
        ),
    ]
