# Generated by Django 4.0.6 on 2022-07-27 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicar', '0005_remove_horarios_data_agendamento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultas',
            old_name='horarios',
            new_name='horario',
        ),
    ]
