# Generated by Django 4.0.6 on 2022-07-27 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicar', '0006_rename_horarios_consultas_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultas',
            name='agenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda', to='medicar.agenda'),
        ),
    ]
