# Generated by Django 4.0.6 on 2022-07-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicar', '0007_alter_consultas_agenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultas',
            name='data_agendamento',
            field=models.DateField(null=True),
        ),
    ]
