# Generated by Django 4.0.6 on 2022-07-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicar', '0009_remove_horarios_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='horarios',
            name='teste_migration',
            field=models.CharField(default='', max_length=1),
            preserve_default=False,
        ),
    ]
