# Generated by Django 4.0.6 on 2022-07-28 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicar', '0010_horarios_teste_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horarios',
            name='teste_migration',
        ),
    ]
