# Generated by Django 4.0.6 on 2022-07-28 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicar', '0012_alter_horarios_unique_together'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Consultas',
            new_name='Consulta',
        ),
        migrations.RenameModel(
            old_name='Horarios',
            new_name='Horario',
        ),
    ]
